### ISSUE TITLE
Brew installation does not work for m1 Macbook pro

### ISSUE THREAD

**Issue by nii236** [TimothyStiles/poly#195] opened 2021-08-28 07:17 UTC
**Describe the bug**

Installation on MacOS via Homebrew does not work. This might be due to m1 vs intel CPUs but I do not own both so can not confirm.

**To Reproduce**

```
➜  Downloads brew install timothystiles/poly/poly

==> Tapping timothystiles/poly
Cloning into '/opt/homebrew/Library/Taps/timothystiles/homebrew-poly'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 80 (delta 20), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (80/80), 9.30 KiB | 2.33 MiB/s, done.
Resolving deltas: 100% (20/20), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/timothystiles/homebrew-poly/Formula/poly.rb
formulae require at least a URL
Error: Cannot tap timothystiles/poly: invalid syntax in tap!
```

**Expected behavior**

Successful installation.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- MacOS 11.4
- M1 Macbook Pro

**Additional Context**

Homebrew list does not seem to contain this project: https://formulae.brew.sh/formula/

**Comment by TimothyStiles** [comment] 2021-08-28 18:03
Thanks for the issue @nii236 . This must have broken when we refactored into a new subpackage scheme. Will take a look at it.

> Additional Context
> Homebrew list does not seem to contain this project: https://formulae.brew.sh/formula/

Reason why we don't appear in homebrew list is because that has to be updated manually while using `timothystiles/poly/poly` can be auto updated using go releaser.

**Comment by TimothyStiles** [comment] 2021-08-30 21:20
@nii236 So I just ran `brew install timothystiles/poly/poly` and it successfully installed the most recent version on my non-M1 Macbook Pro after I uninstalled and cleared download cache.

I don't really know how to reproduce your bug besides what I've tried above. Have you had similar issues with other homebrew formulae?

**Comment by Koeng101** [comment] 2021-08-30 23:15
I have a m1 MacBook I could try it on - though I've just been running poly in a Debian vm on the machine, and it works fine there.

**Comment by TimothyStiles** [comment] 2021-08-31 21:15
@nii236 it looks like @v-raja was running into a similar issue and it may be fixed with our latest release. Give it another try.

**Comment by nii236** [comment] 2021-09-06 09:02
Here's my latest attempt, any ideas?

```
➜  Ledger data leak brew update
Already up-to-date.
➜  Ledger data leak brew install timothystiles/poly/poly

==> Tapping timothystiles/poly
Cloning into '/opt/homebrew/Library/Taps/timothystiles/homebrew-poly'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 84 (delta 21), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (84/84), 9.78 KiB | 2.45 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/timothystiles/homebrew-poly/Formula/poly.rb
formulae require at least a URL
Error: Cannot tap timothystiles/poly: invalid syntax in tap!
➜  Ledger data leak
```

**Comment by nii236** [comment] 2021-09-06 09:02
Here's my latest attempt, any ideas?

```
➜  ~ brew update
Already up-to-date.
➜  ~ brew install timothystiles/poly/poly

==> Tapping timothystiles/poly
Cloning into '/opt/homebrew/Library/Taps/timothystiles/homebrew-poly'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 84 (delta 21), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (84/84), 9.78 KiB | 1.96 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/timothystiles/homebrew-poly/Formula/poly.rb
formulae require at least a URL
Error: Cannot tap timothystiles/poly: invalid syntax in tap!
➜  ~
```

**Comment by Koeng101** [comment] 2021-09-07 14:44
I get the same error on my m1 MacBook Pro. How is brew currently released @TimothyStiles ?

**Comment by TimothyStiles** [comment] 2021-09-10 14:47
@Koeng101 @nii236 

Here's the YML that GoReleaser uses to create our homebrew formula on release
https://github.com/TimothyStiles/poly/blob/11ddbf5282153eed258d313fbb23c2913dd2f9a9/.goreleaser.yml#L63-L76

This automatically pushes a homebrew formula to a separate repo for homebrew to use.

It looks like there's some specific language on the formula that checks to see if it's an intel Mac and ONLY installs if it's an intel Mac. It also looks like we're not actually building binaries for M1 Macbooks so this is likely the problem.

https://github.com/TimothyStiles/homebrew-poly/blob/117c65fc252fef4e76d35d2c9be4c7d7eea35080/Formula/poly.rb#L11-L16

Looks like the solution then is to update our GoReleaser file to build for M1 and that should probably fix the automated formula on release.

**Comment by TimothyStiles** [comment] 2021-09-10 14:53
Looked into it and Goreleaser added M1 support. It also has a ton of targets. Any others I should through in there while I'm at it? 😂 

https://github.com/goreleaser/goreleaser/blob/3338fad7baebf81d90e80b548f4ecf4eb81af97f/internal/builders/golang/targets.go#L129-L135

**Comment by TimothyStiles** [comment] 2021-09-10 21:22
@Koeng101 @nii236 this issue should be fixed with the latest release. Could one of you give it a try and confirm?

https://github.com/TimothyStiles/poly/releases/tag/v0.13.1

**Comment by TimothyStiles** [comment] 2021-09-10 21:28
According to @Koeng101 on our discord this works! Closing.

**Closed by TimothyStiles** 2021-09-10 21:28 UTC
